package udaff.edu.pe.entities;
// Generated 12 nov. 2020 8:24:56 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Allcatalogos generated by hbm2java
 */
@Entity
@Table(name = "allcatalogos", catalog = "bd_mimercado")
public class Allcatalogos implements java.io.Serializable {

	private AllcatalogosId id;

	public Allcatalogos() {
	}

	public Allcatalogos(AllcatalogosId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "PId", column = @Column(name = "p_id", nullable = false)),
			@AttributeOverride(name = "PNombre", column = @Column(name = "p_nombre", length = 45)),
			@AttributeOverride(name = "MId", column = @Column(name = "m_id", nullable = false)),
			@AttributeOverride(name = "MNombre", column = @Column(name = "m_nombre", length = 60)),
			@AttributeOverride(name = "CId", column = @Column(name = "c_id", nullable = false)),
			@AttributeOverride(name = "CTitulo", column = @Column(name = "c_titulo", nullable = false, length = 45)),
			@AttributeOverride(name = "CImagen", column = @Column(name = "c_imagen", length = 200)),
			@AttributeOverride(name = "CPrecio", column = @Column(name = "c_precio", precision = 22, scale = 0)),
			@AttributeOverride(name = "CTipoVenta", column = @Column(name = "c_tipo_venta", nullable = false, length = 45)),
			@AttributeOverride(name = "CCantidad", column = @Column(name = "c_cantidad")),
			@AttributeOverride(name = "CFechaCreada", column = @Column(name = "c_fecha_creada", nullable = false, length = 10)),
			@AttributeOverride(name = "tpId", column = @Column(name = "tp_id", nullable = false)),
			@AttributeOverride(name = "tpNombre", column = @Column(name = "tp_nombre", nullable = false, length = 60)),
			@AttributeOverride(name = "tnId", column = @Column(name = "tn_id", nullable = false)) })
	public AllcatalogosId getId() {
		return this.id;
	}

	public void setId(AllcatalogosId id) {
		this.id = id;
	}

}
