package udaff.edu.pe.entities;
// Generated 12 nov. 2020 0:23:06 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AllcatalogosId generated by hbm2java
 */
@Embeddable
public class AllcatalogosId implements java.io.Serializable {

	private int PId;
	private String PNombre;
	private int MId;
	private String MNombre;
	private int CId;
	private String CTitulo;
	private String CImagen;
	private Double CPrecio;
	private String CTipoVenta;
	private Integer CCantidad;
	private Date CFechaCreada;
	private int tpId;
	private String tpNombre;

	public AllcatalogosId() {
	}

	public AllcatalogosId(int PId, int MId, int CId, String CTitulo, String CTipoVenta, Date CFechaCreada, int tpId,
			String tpNombre) {
		this.PId = PId;
		this.MId = MId;
		this.CId = CId;
		this.CTitulo = CTitulo;
		this.CTipoVenta = CTipoVenta;
		this.CFechaCreada = CFechaCreada;
		this.tpId = tpId;
		this.tpNombre = tpNombre;
	}

	public AllcatalogosId(int PId, String PNombre, int MId, String MNombre, int CId, String CTitulo, String CImagen,
			Double CPrecio, String CTipoVenta, Integer CCantidad, Date CFechaCreada, int tpId, String tpNombre) {
		this.PId = PId;
		this.PNombre = PNombre;
		this.MId = MId;
		this.MNombre = MNombre;
		this.CId = CId;
		this.CTitulo = CTitulo;
		this.CImagen = CImagen;
		this.CPrecio = CPrecio;
		this.CTipoVenta = CTipoVenta;
		this.CCantidad = CCantidad;
		this.CFechaCreada = CFechaCreada;
		this.tpId = tpId;
		this.tpNombre = tpNombre;
	}

	@Column(name = "p_id", nullable = false)
	public int getPId() {
		return this.PId;
	}

	public void setPId(int PId) {
		this.PId = PId;
	}

	@Column(name = "p_nombre", length = 45)
	public String getPNombre() {
		return this.PNombre;
	}

	public void setPNombre(String PNombre) {
		this.PNombre = PNombre;
	}

	@Column(name = "m_id", nullable = false)
	public int getMId() {
		return this.MId;
	}

	public void setMId(int MId) {
		this.MId = MId;
	}

	@Column(name = "m_nombre", length = 60)
	public String getMNombre() {
		return this.MNombre;
	}

	public void setMNombre(String MNombre) {
		this.MNombre = MNombre;
	}

	@Column(name = "c_id", nullable = false)
	public int getCId() {
		return this.CId;
	}

	public void setCId(int CId) {
		this.CId = CId;
	}

	@Column(name = "c_titulo", nullable = false, length = 45)
	public String getCTitulo() {
		return this.CTitulo;
	}

	public void setCTitulo(String CTitulo) {
		this.CTitulo = CTitulo;
	}

	@Column(name = "c_imagen", length = 200)
	public String getCImagen() {
		return this.CImagen;
	}

	public void setCImagen(String CImagen) {
		this.CImagen = CImagen;
	}

	@Column(name = "c_precio", precision = 22, scale = 0)
	public Double getCPrecio() {
		return this.CPrecio;
	}

	public void setCPrecio(Double CPrecio) {
		this.CPrecio = CPrecio;
	}

	@Column(name = "c_tipo_venta", nullable = false, length = 45)
	public String getCTipoVenta() {
		return this.CTipoVenta;
	}

	public void setCTipoVenta(String CTipoVenta) {
		this.CTipoVenta = CTipoVenta;
	}

	@Column(name = "c_cantidad")
	public Integer getCCantidad() {
		return this.CCantidad;
	}

	public void setCCantidad(Integer CCantidad) {
		this.CCantidad = CCantidad;
	}

	@Column(name = "c_fecha_creada", nullable = false, length = 10)
	public Date getCFechaCreada() {
		return this.CFechaCreada;
	}

	public void setCFechaCreada(Date CFechaCreada) {
		this.CFechaCreada = CFechaCreada;
	}

	@Column(name = "tp_id", nullable = false)
	public int getTpId() {
		return this.tpId;
	}

	public void setTpId(int tpId) {
		this.tpId = tpId;
	}

	@Column(name = "tp_nombre", nullable = false, length = 60)
	public String getTpNombre() {
		return this.tpNombre;
	}

	public void setTpNombre(String tpNombre) {
		this.tpNombre = tpNombre;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AllcatalogosId))
			return false;
		AllcatalogosId castOther = (AllcatalogosId) other;

		return (this.getPId() == castOther.getPId())
				&& ((this.getPNombre() == castOther.getPNombre()) || (this.getPNombre() != null
						&& castOther.getPNombre() != null && this.getPNombre().equals(castOther.getPNombre())))
				&& (this.getMId() == castOther.getMId())
				&& ((this.getMNombre() == castOther.getMNombre()) || (this.getMNombre() != null
						&& castOther.getMNombre() != null && this.getMNombre().equals(castOther.getMNombre())))
				&& (this.getCId() == castOther.getCId())
				&& ((this.getCTitulo() == castOther.getCTitulo()) || (this.getCTitulo() != null
						&& castOther.getCTitulo() != null && this.getCTitulo().equals(castOther.getCTitulo())))
				&& ((this.getCImagen() == castOther.getCImagen()) || (this.getCImagen() != null
						&& castOther.getCImagen() != null && this.getCImagen().equals(castOther.getCImagen())))
				&& ((this.getCPrecio() == castOther.getCPrecio()) || (this.getCPrecio() != null
						&& castOther.getCPrecio() != null && this.getCPrecio().equals(castOther.getCPrecio())))
				&& ((this.getCTipoVenta() == castOther.getCTipoVenta()) || (this.getCTipoVenta() != null
						&& castOther.getCTipoVenta() != null && this.getCTipoVenta().equals(castOther.getCTipoVenta())))
				&& ((this.getCCantidad() == castOther.getCCantidad()) || (this.getCCantidad() != null
						&& castOther.getCCantidad() != null && this.getCCantidad().equals(castOther.getCCantidad())))
				&& ((this.getCFechaCreada() == castOther.getCFechaCreada())
						|| (this.getCFechaCreada() != null && castOther.getCFechaCreada() != null
								&& this.getCFechaCreada().equals(castOther.getCFechaCreada())))
				&& (this.getTpId() == castOther.getTpId())
				&& ((this.getTpNombre() == castOther.getTpNombre()) || (this.getTpNombre() != null
						&& castOther.getTpNombre() != null && this.getTpNombre().equals(castOther.getTpNombre())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPId();
		result = 37 * result + (getPNombre() == null ? 0 : this.getPNombre().hashCode());
		result = 37 * result + this.getMId();
		result = 37 * result + (getMNombre() == null ? 0 : this.getMNombre().hashCode());
		result = 37 * result + this.getCId();
		result = 37 * result + (getCTitulo() == null ? 0 : this.getCTitulo().hashCode());
		result = 37 * result + (getCImagen() == null ? 0 : this.getCImagen().hashCode());
		result = 37 * result + (getCPrecio() == null ? 0 : this.getCPrecio().hashCode());
		result = 37 * result + (getCTipoVenta() == null ? 0 : this.getCTipoVenta().hashCode());
		result = 37 * result + (getCCantidad() == null ? 0 : this.getCCantidad().hashCode());
		result = 37 * result + (getCFechaCreada() == null ? 0 : this.getCFechaCreada().hashCode());
		result = 37 * result + this.getTpId();
		result = 37 * result + (getTpNombre() == null ? 0 : this.getTpNombre().hashCode());
		return result;
	}

}
