package udaff.edu.pe.entities;
// Generated 12 nov. 2020 8:24:56 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Allpuestos generated by hbm2java
 */
@Entity
@Table(name = "allpuestos", catalog = "bd_mimercado")
public class Allpuestos implements java.io.Serializable {

	private AllpuestosId id;

	public Allpuestos() {
	}

	public Allpuestos(AllpuestosId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "MId", column = @Column(name = "m_id", nullable = false)),
			@AttributeOverride(name = "MNombre", column = @Column(name = "m_nombre", length = 60)),
			@AttributeOverride(name = "PId", column = @Column(name = "p_id", nullable = false)),
			@AttributeOverride(name = "PImagen", column = @Column(name = "p_imagen", length = 100)),
			@AttributeOverride(name = "PNombre", column = @Column(name = "p_nombre", length = 45)),
			@AttributeOverride(name = "PDescripcion", column = @Column(name = "p_descripcion", length = 500)),
			@AttributeOverride(name = "tnId", column = @Column(name = "tn_id", nullable = false)),
			@AttributeOverride(name = "tnNombre", column = @Column(name = "tn_nombre", nullable = false, length = 70)),
			@AttributeOverride(name = "PEstado", column = @Column(name = "p_estado")) })
	public AllpuestosId getId() {
		return this.id;
	}

	public void setId(AllpuestosId id) {
		this.id = id;
	}

}
