package udaff.edu.pe.entities;
// Generated 12 nov. 2020 8:24:56 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Compra generated by hbm2java
 */
@Entity
@Table(name = "compra", catalog = "bd_mimercado", uniqueConstraints = @UniqueConstraint(columnNames = "codigo_compra"))
public class Compra implements java.io.Serializable {

	private int idCompra;
	private Usuario usuario;
	private String codigoCompra;
	private int idCatalogo;
	private int cantidad;
	private double precioUnitario;
	private Double precioTotal;
	private Date fechaCompra;

	public Compra() {
	}

	public Compra(int idCompra, Usuario usuario, String codigoCompra, int idCatalogo, int cantidad,
			double precioUnitario) {
		this.idCompra = idCompra;
		this.usuario = usuario;
		this.codigoCompra = codigoCompra;
		this.idCatalogo = idCatalogo;
		this.cantidad = cantidad;
		this.precioUnitario = precioUnitario;
	}

	public Compra(int idCompra, Usuario usuario, String codigoCompra, int idCatalogo, int cantidad,
			double precioUnitario, Double precioTotal, Date fechaCompra) {
		this.idCompra = idCompra;
		this.usuario = usuario;
		this.codigoCompra = codigoCompra;
		this.idCatalogo = idCatalogo;
		this.cantidad = cantidad;
		this.precioUnitario = precioUnitario;
		this.precioTotal = precioTotal;
		this.fechaCompra = fechaCompra;
	}

	@Id

	@Column(name = "id_compra", unique = true, nullable = false)
	public int getIdCompra() {
		return this.idCompra;
	}

	public void setIdCompra(int idCompra) {
		this.idCompra = idCompra;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "codigo_compra", unique = true, nullable = false, length = 10)
	public String getCodigoCompra() {
		return this.codigoCompra;
	}

	public void setCodigoCompra(String codigoCompra) {
		this.codigoCompra = codigoCompra;
	}

	@Column(name = "id_catalogo", nullable = false)
	public int getIdCatalogo() {
		return this.idCatalogo;
	}

	public void setIdCatalogo(int idCatalogo) {
		this.idCatalogo = idCatalogo;
	}

	@Column(name = "cantidad", nullable = false)
	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "precio_unitario", nullable = false, precision = 22, scale = 0)
	public double getPrecioUnitario() {
		return this.precioUnitario;
	}

	public void setPrecioUnitario(double precioUnitario) {
		this.precioUnitario = precioUnitario;
	}

	@Column(name = "precio_total", precision = 22, scale = 0)
	public Double getPrecioTotal() {
		return this.precioTotal;
	}

	public void setPrecioTotal(Double precioTotal) {
		this.precioTotal = precioTotal;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_compra", length = 10)
	public Date getFechaCompra() {
		return this.fechaCompra;
	}

	public void setFechaCompra(Date fechaCompra) {
		this.fechaCompra = fechaCompra;
	}

}
