package udaff.edu.pe.entities;
// Generated 12 nov. 2020 8:24:56 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LoginId generated by hbm2java
 */
@Embeddable
public class LoginId implements java.io.Serializable {

	private int userId;
	private String userCuenta;
	private String userClave;
	private String userNombreCuenta;
	private String userEmail;
	private String userNombre;
	private String userApellido;
	private Integer userEdad;
	private int perfilId;

	public LoginId() {
	}

	public LoginId(int userId, String userCuenta, String userClave, String userNombreCuenta, String userEmail,
			int perfilId) {
		this.userId = userId;
		this.userCuenta = userCuenta;
		this.userClave = userClave;
		this.userNombreCuenta = userNombreCuenta;
		this.userEmail = userEmail;
		this.perfilId = perfilId;
	}

	public LoginId(int userId, String userCuenta, String userClave, String userNombreCuenta, String userEmail,
			String userNombre, String userApellido, Integer userEdad, int perfilId) {
		this.userId = userId;
		this.userCuenta = userCuenta;
		this.userClave = userClave;
		this.userNombreCuenta = userNombreCuenta;
		this.userEmail = userEmail;
		this.userNombre = userNombre;
		this.userApellido = userApellido;
		this.userEdad = userEdad;
		this.perfilId = perfilId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "user_cuenta", nullable = false, length = 25)
	public String getUserCuenta() {
		return this.userCuenta;
	}

	public void setUserCuenta(String userCuenta) {
		this.userCuenta = userCuenta;
	}

	@Column(name = "user_clave", nullable = false, length = 50)
	public String getUserClave() {
		return this.userClave;
	}

	public void setUserClave(String userClave) {
		this.userClave = userClave;
	}

	@Column(name = "user_nombre_cuenta", nullable = false, length = 25)
	public String getUserNombreCuenta() {
		return this.userNombreCuenta;
	}

	public void setUserNombreCuenta(String userNombreCuenta) {
		this.userNombreCuenta = userNombreCuenta;
	}

	@Column(name = "user_email", nullable = false, length = 45)
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Column(name = "user_nombre", length = 45)
	public String getUserNombre() {
		return this.userNombre;
	}

	public void setUserNombre(String userNombre) {
		this.userNombre = userNombre;
	}

	@Column(name = "user_apellido", length = 45)
	public String getUserApellido() {
		return this.userApellido;
	}

	public void setUserApellido(String userApellido) {
		this.userApellido = userApellido;
	}

	@Column(name = "user_edad")
	public Integer getUserEdad() {
		return this.userEdad;
	}

	public void setUserEdad(Integer userEdad) {
		this.userEdad = userEdad;
	}

	@Column(name = "perfil_id", nullable = false)
	public int getPerfilId() {
		return this.perfilId;
	}

	public void setPerfilId(int perfilId) {
		this.perfilId = perfilId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LoginId))
			return false;
		LoginId castOther = (LoginId) other;

		return (this.getUserId() == castOther.getUserId())
				&& ((this.getUserCuenta() == castOther.getUserCuenta()) || (this.getUserCuenta() != null
						&& castOther.getUserCuenta() != null && this.getUserCuenta().equals(castOther.getUserCuenta())))
				&& ((this.getUserClave() == castOther.getUserClave()) || (this.getUserClave() != null
						&& castOther.getUserClave() != null && this.getUserClave().equals(castOther.getUserClave())))
				&& ((this.getUserNombreCuenta() == castOther.getUserNombreCuenta())
						|| (this.getUserNombreCuenta() != null && castOther.getUserNombreCuenta() != null
								&& this.getUserNombreCuenta().equals(castOther.getUserNombreCuenta())))
				&& ((this.getUserEmail() == castOther.getUserEmail()) || (this.getUserEmail() != null
						&& castOther.getUserEmail() != null && this.getUserEmail().equals(castOther.getUserEmail())))
				&& ((this.getUserNombre() == castOther.getUserNombre()) || (this.getUserNombre() != null
						&& castOther.getUserNombre() != null && this.getUserNombre().equals(castOther.getUserNombre())))
				&& ((this.getUserApellido() == castOther.getUserApellido())
						|| (this.getUserApellido() != null && castOther.getUserApellido() != null
								&& this.getUserApellido().equals(castOther.getUserApellido())))
				&& ((this.getUserEdad() == castOther.getUserEdad()) || (this.getUserEdad() != null
						&& castOther.getUserEdad() != null && this.getUserEdad().equals(castOther.getUserEdad())))
				&& (this.getPerfilId() == castOther.getPerfilId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + (getUserCuenta() == null ? 0 : this.getUserCuenta().hashCode());
		result = 37 * result + (getUserClave() == null ? 0 : this.getUserClave().hashCode());
		result = 37 * result + (getUserNombreCuenta() == null ? 0 : this.getUserNombreCuenta().hashCode());
		result = 37 * result + (getUserEmail() == null ? 0 : this.getUserEmail().hashCode());
		result = 37 * result + (getUserNombre() == null ? 0 : this.getUserNombre().hashCode());
		result = 37 * result + (getUserApellido() == null ? 0 : this.getUserApellido().hashCode());
		result = 37 * result + (getUserEdad() == null ? 0 : this.getUserEdad().hashCode());
		result = 37 * result + this.getPerfilId();
		return result;
	}

}
