package udaff.edu.pe.entities;
// Generated 12 nov. 2020 0:23:06 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Login generated by hbm2java
 */
@Entity
@Table(name = "login", catalog = "bd_mimercado")
public class Login implements java.io.Serializable {

	private LoginId id;

	public Login() {
	}

	public Login(LoginId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)),
			@AttributeOverride(name = "userCuenta", column = @Column(name = "user_cuenta", nullable = false, length = 25)),
			@AttributeOverride(name = "userClave", column = @Column(name = "user_clave", nullable = false, length = 50)),
			@AttributeOverride(name = "userNombreCuenta", column = @Column(name = "user_nombre_cuenta", nullable = false, length = 25)),
			@AttributeOverride(name = "userEmail", column = @Column(name = "user_email", nullable = false, length = 45)),
			@AttributeOverride(name = "userNombre", column = @Column(name = "user_nombre", length = 45)),
			@AttributeOverride(name = "userApellido", column = @Column(name = "user_apellido", length = 45)),
			@AttributeOverride(name = "userEdad", column = @Column(name = "user_edad")),
			@AttributeOverride(name = "perfilId", column = @Column(name = "perfil_id", nullable = false)) })
	public LoginId getId() {
		return this.id;
	}

	public void setId(LoginId id) {
		this.id = id;
	}

}
