package udaff.edu.pe.entities;
// Generated 6 nov. 2020 12:04:27 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Puesto generated by hbm2java
 */
@Entity
@Table(name = "puesto", catalog = "bd_mimercado")
public class Puesto implements java.io.Serializable {

	private int idpuesto;
	private TipoNegocio tipoNegocio;
	private Usuario usuario;
	private String nombre;
	private String imagen;
	private String descripcion;
	private Boolean estado;
	private Date fechaCreada;
	private int idmercado;
	private Set<Catalogo> catalogos = new HashSet<Catalogo>(0);

	public Puesto() {
	}

	public Puesto(TipoNegocio tipoNegocio, Usuario usuario, Date fechaCreada, int idmercado) {
		this.tipoNegocio = tipoNegocio;
		this.usuario = usuario;
		this.fechaCreada = fechaCreada;
		this.idmercado = idmercado;
	}

	public Puesto(TipoNegocio tipoNegocio, Usuario usuario, String nombre, String imagen, String descripcion,
			Boolean estado, Date fechaCreada, int idmercado, Set<Catalogo> catalogos) {
		this.tipoNegocio = tipoNegocio;
		this.usuario = usuario;
		this.nombre = nombre;
		this.imagen = imagen;
		this.descripcion = descripcion;
		this.estado = estado;
		this.fechaCreada = fechaCreada;
		this.idmercado = idmercado;
		this.catalogos = catalogos;
	}

	@GenericGenerator(name = "udaff.edu.pe.entities.PuestoIdGenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "usuario"))
	@Id
	@GeneratedValue(generator = "udaff.edu.pe.entities.PuestoIdGenerator")

	@Column(name = "idpuesto", unique = true, nullable = false)
	public int getIdpuesto() {
		return this.idpuesto;
	}

	public void setIdpuesto(int idpuesto) {
		this.idpuesto = idpuesto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_negocio", nullable = false)
	public TipoNegocio getTipoNegocio() {
		return this.tipoNegocio;
	}

	public void setTipoNegocio(TipoNegocio tipoNegocio) {
		this.tipoNegocio = tipoNegocio;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "imagen", length = 100)
	public String getImagen() {
		return this.imagen;
	}

	public void setImagen(String imagen) {
		this.imagen = imagen;
	}

	@Column(name = "descripcion", length = 500)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "estado")
	public Boolean getEstado() {
		return this.estado;
	}

	public void setEstado(Boolean estado) {
		this.estado = estado;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_creada", nullable = false, length = 10)
	public Date getFechaCreada() {
		return this.fechaCreada;
	}

	public void setFechaCreada(Date fechaCreada) {
		this.fechaCreada = fechaCreada;
	}

	@Column(name = "idmercado", nullable = false)
	public int getIdmercado() {
		return this.idmercado;
	}

	public void setIdmercado(int idmercado) {
		this.idmercado = idmercado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "puesto")
	public Set<Catalogo> getCatalogos() {
		return this.catalogos;
	}

	public void setCatalogos(Set<Catalogo> catalogos) {
		this.catalogos = catalogos;
	}

}
