package udaff.edu.pe.entities;
// Generated 6 nov. 2020 12:04:27 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TipoProducto generated by hbm2java
 */
@Entity
@Table(name = "tipo_producto", catalog = "bd_mimercado")
public class TipoProducto implements java.io.Serializable {

	private Integer idTipoProducto;
	@JsonIgnore
	private TipoNegocio tipoNegocio;
	private String nombre;

	public TipoProducto() {
	}

	public TipoProducto(TipoNegocio tipoNegocio, String nombre) {
		this.tipoNegocio = tipoNegocio;
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_tipo_producto", unique = true, nullable = false)
	public Integer getIdTipoProducto() {
		return this.idTipoProducto;
	}

	public void setIdTipoProducto(Integer idTipoProducto) {
		this.idTipoProducto = idTipoProducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_negocio", nullable = false)
	public TipoNegocio getTipoNegocio() {
		return this.tipoNegocio;
	}

	public void setTipoNegocio(TipoNegocio tipoNegocio) {
		this.tipoNegocio = tipoNegocio;
	}

	@Column(name = "nombre", nullable = false, length = 60)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
