package udaff.edu.pe.entities;
// Generated 12 nov. 2020 8:24:56 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoVenta generated by hbm2java
 */
@Entity
@Table(name = "tipo_venta", catalog = "bd_mimercado")
public class TipoVenta implements java.io.Serializable {

	private Integer idTipoVenta;
	private String nombre;
	private String abrev;
	private Set<Catalogo> catalogos = new HashSet<Catalogo>(0);

	public TipoVenta() {
	}

	public TipoVenta(String nombre, String abrev) {
		this.nombre = nombre;
		this.abrev = abrev;
	}

	public TipoVenta(String nombre, String abrev, Set<Catalogo> catalogos) {
		this.nombre = nombre;
		this.abrev = abrev;
		this.catalogos = catalogos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_tipo_venta", unique = true, nullable = false)
	public Integer getIdTipoVenta() {
		return this.idTipoVenta;
	}

	public void setIdTipoVenta(Integer idTipoVenta) {
		this.idTipoVenta = idTipoVenta;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "abrev", nullable = false, length = 45)
	public String getAbrev() {
		return this.abrev;
	}

	public void setAbrev(String abrev) {
		this.abrev = abrev;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoVenta")
	public Set<Catalogo> getCatalogos() {
		return this.catalogos;
	}

	public void setCatalogos(Set<Catalogo> catalogos) {
		this.catalogos = catalogos;
	}

}
