package udaff.edu.pe.entities;
// Generated 12 nov. 2020 0:23:06 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * TipoNegocio generated by hbm2java
 */
@Entity
@Table(name = "tipo_negocio", catalog = "bd_mimercado")
public class TipoNegocio implements java.io.Serializable {

	private Integer idTipoNegocio;
	private String nombre;
	@JsonIgnore
	private Set<Puesto> puestos = new HashSet<Puesto>(0);
	@JsonIgnore
	private Set<TipoProducto> tipoProductos = new HashSet<TipoProducto>(0);

	public TipoNegocio() {
	}

	public TipoNegocio(String nombre) {
		this.nombre = nombre;
	}

	public TipoNegocio(String nombre, Set<Puesto> puestos, Set<TipoProducto> tipoProductos) {
		this.nombre = nombre;
		this.puestos = puestos;
		this.tipoProductos = tipoProductos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_tipo_negocio", unique = true, nullable = false)
	public Integer getIdTipoNegocio() {
		return this.idTipoNegocio;
	}

	public void setIdTipoNegocio(Integer idTipoNegocio) {
		this.idTipoNegocio = idTipoNegocio;
	}

	@Column(name = "nombre", nullable = false, length = 70)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoNegocio")
	public Set<Puesto> getPuestos() {
		return this.puestos;
	}

	public void setPuestos(Set<Puesto> puestos) {
		this.puestos = puestos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoNegocio")
	public Set<TipoProducto> getTipoProductos() {
		return this.tipoProductos;
	}

	public void setTipoProductos(Set<TipoProducto> tipoProductos) {
		this.tipoProductos = tipoProductos;
	}

}
