package udaff.edu.pe.entities;
// Generated 12 nov. 2020 8:24:56 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UsersessionId generated by hbm2java
 */
@Embeddable
public class UsersessionId implements java.io.Serializable {

	private int id;
	private String cuenta;
	private String clave;
	private String email;
	private String nombreCuenta;
	private String nombre;
	private String apellido;
	private Integer edad;

	public UsersessionId() {
	}

	public UsersessionId(int id, String cuenta, String clave, String email, String nombreCuenta) {
		this.id = id;
		this.cuenta = cuenta;
		this.clave = clave;
		this.email = email;
		this.nombreCuenta = nombreCuenta;
	}

	public UsersessionId(int id, String cuenta, String clave, String email, String nombreCuenta, String nombre,
			String apellido, Integer edad) {
		this.id = id;
		this.cuenta = cuenta;
		this.clave = clave;
		this.email = email;
		this.nombreCuenta = nombreCuenta;
		this.nombre = nombre;
		this.apellido = apellido;
		this.edad = edad;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "cuenta", nullable = false, length = 25)
	public String getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(String cuenta) {
		this.cuenta = cuenta;
	}

	@Column(name = "clave", nullable = false, length = 50)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "nombre_cuenta", nullable = false, length = 25)
	public String getNombreCuenta() {
		return this.nombreCuenta;
	}

	public void setNombreCuenta(String nombreCuenta) {
		this.nombreCuenta = nombreCuenta;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido", length = 45)
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Column(name = "edad")
	public Integer getEdad() {
		return this.edad;
	}

	public void setEdad(Integer edad) {
		this.edad = edad;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsersessionId))
			return false;
		UsersessionId castOther = (UsersessionId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getCuenta() == castOther.getCuenta()) || (this.getCuenta() != null
						&& castOther.getCuenta() != null && this.getCuenta().equals(castOther.getCuenta())))
				&& ((this.getClave() == castOther.getClave()) || (this.getClave() != null
						&& castOther.getClave() != null && this.getClave().equals(castOther.getClave())))
				&& ((this.getEmail() == castOther.getEmail()) || (this.getEmail() != null
						&& castOther.getEmail() != null && this.getEmail().equals(castOther.getEmail())))
				&& ((this.getNombreCuenta() == castOther.getNombreCuenta())
						|| (this.getNombreCuenta() != null && castOther.getNombreCuenta() != null
								&& this.getNombreCuenta().equals(castOther.getNombreCuenta())))
				&& ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
						&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())))
				&& ((this.getApellido() == castOther.getApellido()) || (this.getApellido() != null
						&& castOther.getApellido() != null && this.getApellido().equals(castOther.getApellido())))
				&& ((this.getEdad() == castOther.getEdad()) || (this.getEdad() != null && castOther.getEdad() != null
						&& this.getEdad().equals(castOther.getEdad())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getCuenta() == null ? 0 : this.getCuenta().hashCode());
		result = 37 * result + (getClave() == null ? 0 : this.getClave().hashCode());
		result = 37 * result + (getEmail() == null ? 0 : this.getEmail().hashCode());
		result = 37 * result + (getNombreCuenta() == null ? 0 : this.getNombreCuenta().hashCode());
		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result + (getApellido() == null ? 0 : this.getApellido().hashCode());
		result = 37 * result + (getEdad() == null ? 0 : this.getEdad().hashCode());
		return result;
	}

}
